In [2]:
!pip install numpy


[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.7 MB ? eta -:--:--
    --------------------------------------- 0.3/12.7 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/12.7 MB 3.1 MB/s eta 0:00:04
   ------------ --------------------------- 3.9/12.7 MB 6.4 MB/s eta 0:00:02
   --------------------- ------------------ 6.8/12.7 MB 8.5 MB/s eta 0:00:01
   --------------------------------- ------ 10.7/12.7 MB 10.4 MB/s eta 0:00:01
   ---------------------------------------- 12.7/12.7 MB 10.7 MB/s  0:00:01



[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [ ]:
import numpy as np
import time

In [ ]:
arr = np.array([[1,2,3],[4,5,6]])
print(arr.shape) # 2 rows x 3 columns
print(arr.ndim) # 2 dimension array
print(arr.dtype) # int64

(2, 3)
2
int64


In [5]:
py_list = list(range(1_000_000))
py_result = []
start_time = time.time()
for i in py_list:
	py_result.append(i+5)
end_time = time.time()
print("Python List Time:", end_time - start_time)

Python List Time: 1.4521842002868652


In [7]:
np_array = np.arange(1_000_000)
start_time = time.time()
np_result = np_array + 5
end_time = time.time()
print("Numpy Array Time:", end_time - start_time)

Numpy Array Time: 0.006860017776489258


## Creating Arrays in Numpy

In [8]:
arr = np.array([1,2,3])
print(arr)

[1 2 3]


In [9]:
print(np.zeros((2,3)))

[[0. 0. 0.]
 [0. 0. 0.]]


In [10]:
print(np.ones((2,3)))

[[1. 1. 1.]
 [1. 1. 1.]]


In [11]:
print(np.full((2,3), 7)) # first arg -> dimension, second arg -> inital value

[[7 7 7]
 [7 7 7]]


In [13]:
print(np.arange(0,10,2))

[0 2 4 6 8]


In [14]:
print(np.linspace(0,1,5))

[0.   0.25 0.5  0.75 1.  ]


In [15]:
print(np.eye(3))

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [16]:
print(np.diag([1,2,3]))

[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [17]:
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [18]:
arr = np.array([1.5, 2.7, 3.9])
print(arr.astype(int))

[1 2 3]


## NumPy Indexing, Slicing & Strides

In [19]:
arr = np.array([[10, 20, 30],
                [40, 50, 60],
                [70, 80, 90]
            	])

In [20]:
print(arr[0, 1]) # 0 row 1 col
print(arr[2, 2])

20
90


In [21]:
print(arr[-1,-2]) # last row, 2nd last column
print(arr[-3, -3])

80
10


In [ ]:
# general form: arr[start: stop: step]
print(arr[0:2, 1:3]) # rows 0-1, cols 1-2

[[20 30]
 [50 60]]


In [23]:
print(arr[::2, ::2]) #every 2nd row & 2nd column

[[10 30]
 [70 90]]


In [24]:
slice_arr = arr[0, :2] # view (not a copy)
slice_arr[0] = 999

In [28]:
print(arr[0])

[999  20  30]


In [29]:
copy_arr = arr[1].copy() # independent copy
copy_arr[0] = 255

In [30]:
print(arr[1])

[40 50 60]


## NumPy Random Numbers, Reproducibility & Performance Tips

#### Random Number generation
It produces only numbers randomly.

#### Seed
A seed is an initial values that helps detemine the sequence of random numbers

In [36]:
# Simulate 100k coin flips
rng = np.random.default_rng(seed=45)
flips = rng.integers(0,2, size = 100000)
prob_heads = np.mean(flips)
print("Estimated probability of heads:", prob_heads)

Estimated probability of heads: 0.49829


In [37]:
import time

# Python Loop
start = time.time()
squares = [i**2 for i in range(1000000)]
end = time.time()
print("Loop Time:", end - start)

# Numpy vectorized Loop
start = time.time()
arr = np.arange(1000000)
squares_np = arr**2
end = time.time()
print("Vectorized Time:", end - start)

Loop Time: 0.47501444816589355
Vectorized Time: 0.015334606170654297
